import monstera from "../assets/monstera.jpg";
import ficus from "../assets/ficus.jpeg";
import pothos from "../assets/pothos.jpeg";
import aloe from "../assets/aloe.jpeg";
import basilic from "../assets/basilic.jpeg";
import geranium from "../assets/geranium.jpeg";
import olivier from "../assets/olivier.jpeg";
import succulente from "../assets/succulente.png";
import yucca from "../assets/yucca.jpeg";

export const plantList = [
  {
    name: "monstera",
    category: "classique",
    id: "1ed",
    isBestSale: true,
    isSpecialOffer: true,
    wather: 3,
    light: 2,
    cover: monstera,
    price: 15,
  },
  {
    name: "ficus lyrata",
    category: "classique",
    id: "2ab",
    isBestSale: false,
    isSpecialOffer: false,
    wather: 1,
    light: 3,
    cover: ficus,
    price: 16,
  },
  {
    name: "pothos argenté",
    category: "classique",
    id: "3sd",
    isBestSale: false,
    isSpecialOffer: false,
    wather: 2,
    light: 1,
    cover: pothos,
    price: 9,
  },
  {
    name: "yucca",
    category: "classique",
    id: "4kk",
    isBestSale: false,
    isSpecialOffer: true,
    wather: 1,
    light: 3,
    cover: yucca,
    price: 20,
  },
  {
    name: "olivier",
    category: "extérieur",
    id: "5pl",
    isBestSale: false,
    isSpecialOffer: false,
    wather: 1,
    light: 3,
    cover: olivier,
    price: 25,
  },
  {
    name: "géranium",
    category: "extérieur",
    id: "6uo",
    isBestSale: false,
    isSpecialOffer: false,
    wather: 2,
    light: 2,
    cover: geranium,
    price: 13,
  },
  {
    name: "basilique",
    category: "extérieur",
    id: "7ie",
    isBestSale: true,
    isSpecialOffer: false,
    wather: 3,
    light: 2,
    cover: basilic,
    price: 6,
  },
  {
    name: "aloe",
    category: "plante grasse",
    id: "8fp",
    isBestSale: false,
    isSpecialOffer: false,
    wather: 1,
    light: 2,
    cover: aloe,
    price: 21,
  },
  {
    name: "succulente",
    category: "plante grasse",
    id: "9vn",
    isBestSale: false,
    isSpecialOffer: true,
    wather: 1,
    light: 2,
    cover: succulente,
    price: 11,
  },
];
