export const plantList = [
  {
    name: "monstera",
    category: "classique",
    id: "1ed",
    isBestSale: true,
    isSpecialOffer: true,
    wather: 1,
    light: 2,
  },
  {
    name: "ficus lyrata",
    category: "classique",
    id: "2ab",
    isBestSale: false,
    isSpecialOffer: false,
    wather: 3,
    light: 2,
  },
  {
    name: "pothos argenté",
    category: "classique",
    id: "3sd",
    isBestSale: false,
    isSpecialOffer: false,
    wather: 2,
    light: 3,
  },
  {
    name: "yucca",
    category: "classique",
    id: "4kk",
    isBestSale: false,
    isSpecialOffer: true,
    wather: 1,
    light: 1,
  },
  {
    name: "olivier",
    category: "extérieur",
    id: "5pl",
    isBestSale: false,
    isSpecialOffer: false,
    wather: 3,
    light: 1,
  },
  {
    name: "géranium",
    category: "extérieur",
    id: "6uo",
    isBestSale: false,
    isSpecialOffer: false,
    wather: 2,
    light: 3,
  },
  {
    name: "basilique",
    category: "extérieur",
    id: "7ie",
    isBestSale: true,
    isSpecialOffer: false,
    wather: 3,
    light: 3,
  },
  {
    name: "aloe",
    category: "plante grasse",
    id: "8fp",
    isBestSale: false,
    isSpecialOffer: false,
    wather: 1,
    light: 3,
  },
  {
    name: "succulente",
    category: "plante grasse",
    id: "9vn",
    isBestSale: false,
    isSpecialOffer: true,
    wather: 2,
    light: 1,
  },
];
